In [1]:
#####
# Let's begin by exploring the datasets

In [2]:
import pandas as pd
import numpy as np
import sys
import os.path

In [3]:
pd.set_option("display.max_rows", 1000)

In [4]:
lyrics = pd.read_csv("Sources/lyrics-data.csv")
artists = pd.read_csv("Sources/artists-data.csv")
LYRIC_URL = "https://www.vagalume.com"

In [5]:
artists

,Artist,Genres,Songs,Popularity,Link
0,Ivete Sangalo,Pop; Axé; Romântico,313.0,4.4,/ivete-sangalo/
1,Chiclete com Banana,Axé,268.0,3.8,/chiclete-com-banana/
2,Banda Eva,Axé; Romântico; Reggae,215.0,2.3,/banda-eva/
3,É O Tchan,Axé,129.0,1.6,/e-o-tchan/
4,Claudia Leitte,Pop; Axé; Romântico,167.0,1.5,/claudia-leitte/
...,...,...,...,...,...
4163,Miriam Makeba,World Music; Black Music; Blues,17.0,0.0,/miriam-makeba/
4164,Freddie Aguilar,World Music,61.0,0.0,/freddie-aguilar/
4165,Amadou & Mariam,World Music,14.0,0.0,/amadou-mariam/
4166,Magic System,World Music; Gospel/Religioso,16.0,0.0,/magic-system/
4167,Johnny Clegg,World Music; Gospel/Religioso,34.0,0.0,/clegg-johnny/

In [6]:
lyrics

,ALink,SName,SLink,Lyric,language
0,/ivete-sangalo/,Arerê,/ivete-sangalo/arere.html,"Tudo o que eu quero nessa vida,\nToda vida, é\...",pt
1,/ivete-sangalo/,Se Eu Não Te Amasse Tanto Assim,/ivete-sangalo/se-eu-nao-te-amasse-tanto-assim...,Meu coração\nSem direção\nVoando só por voar\n...,pt
2,/ivete-sangalo/,Céu da Boca,/ivete-sangalo/chupa-toda.html,É de babaixá!\nÉ de balacubaca!\nÉ de babaixá!...,pt
3,/ivete-sangalo/,Quando A Chuva Passar,/ivete-sangalo/quando-a-chuva-passar.html,Quando a chuva passar\n\nPra quê falar\nSe voc...,pt
4,/ivete-sangalo/,Sorte Grande,/ivete-sangalo/sorte-grande.html,A minha sorte grande foi você cair do céu\nMin...,pt
...,...,...,...,...,...
379926,/clegg-johnny/,The Waiting,/clegg-johnny/the-waiting.html,Chorus\nHere we stand waiting on the plain\nDa...,en
379927,/clegg-johnny/,Too Early For The Sky,/clegg-johnny/too-early-for-the-sky.html,I nearly disappeared into the mouth of a croco...,en
379928,/clegg-johnny/,Warsaw 1943 (I Never Betrayed The Revolution),/clegg-johnny/warsaw-1943-i-never-betrayed-the...,"Amambuka, amambuka azothengisa izwe lakithi, i...",en
379929,/clegg-johnny/,When The System Has Fallen,/clegg-johnny/when-the-system-has-fallen.html,Sweat in the heat for days on end\nwaiting for...,en
379930,/clegg-johnny/,Woman Be My Country,/clegg-johnny/woman-be-my-country.html,Here we stand on the edge of the day\nFaces me...,en

In [7]:
#####
# Let's fix the genres

In [8]:
#
# convert genres to array
#

def delimit_genres(li):
    ret_arr = []
    for line in li:
        ret_arr.append(str(line).split(';'))
    return ret_arr

artists['Genres'] = delimit_genres(artists['Genres'])
print(artists.shape)
artists.head()

(4168, 5)

,Artist,Genres,Songs,Popularity,Link
0,Ivete Sangalo,"[Pop, Axé, Romântico]",313.0,4.4,/ivete-sangalo/
1,Chiclete com Banana,[Axé],268.0,3.8,/chiclete-com-banana/
2,Banda Eva,"[Axé, Romântico, Reggae]",215.0,2.3,/banda-eva/
3,É O Tchan,[Axé],129.0,1.6,/e-o-tchan/
4,Claudia Leitte,"[Pop, Axé, Romântico]",167.0,1.5,/claudia-leitte/

In [9]:
#
# Only get English lyrics
#

lyrics = lyrics[lyrics['language'] == 'en']
lyrics.reset_index(drop=True, inplace=True)
print(lyrics.shape)
lyrics.head()

(191814, 5)

,ALink,SName,SLink,Lyric,language
0,/ivete-sangalo/,Careless Whisper,/ivete-sangalo/careless-whisper.html,I feel so unsure\nAs I take your hand and lead...,en
1,/ivete-sangalo/,Could You Be Loved / Citação Musical do Rap: S...,/ivete-sangalo/could-you-be-loved-citacao-musi...,"Don't let them fool, ya\nOr even try to school...",en
2,/ivete-sangalo/,Cruisin' (Part. Saulo),/ivete-sangalo/cruisin-part-saulo.html,"Baby, let's cruise, away from here\nDon't be c...",en
3,/ivete-sangalo/,Easy,/ivete-sangalo/easy.html,"Know it sounds funny\nBut, I just can't stand ...",en
4,/ivete-sangalo/,For Your Babies (The Voice cover),/ivete-sangalo/for-your-babies-the-voice-cover...,You've got that look again\nThe one I hoped I ...,en

In [10]:
#
# filter out any artists that don't contain English songs
# (takes some time)
#

for i in range(len(artists)):
    link = artists['Link'][i]
    lyrics_temp = lyrics[lyrics['ALink'] == link]
    temptable = lyrics_temp[lyrics_temp['language'] == 'en']
    if temptable.empty:
        artists.drop(artists.loc[artists['Link'] == link].index, inplace=True)
artists.reset_index(drop=True, inplace=True)
lyrics.drop(['language'], axis=1, inplace=True)
artists

C:\Users\shull\anaconda3\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,Artist,Genres,Songs,Popularity,Link
0,Ivete Sangalo,"[Pop, Axé, Romântico]",313.0,4.4,/ivete-sangalo/
1,Claudia Leitte,"[Pop, Axé, Romântico]",167.0,1.5,/claudia-leitte/
2,Daniela Mercury,"[MPB, Axé]",230.0,1.4,/daniela-mercury/
3,Olodum,[Axé],74.0,1.3,/olodum/
4,Carlinhos Brown,[Axé],111.0,1.4,/carlinhos-brown/
...,...,...,...,...,...
2484,Youssou N'dour,"[World Music, Indie, New Age]",16.0,0.0,/youssou-ndour/
2485,Ofra Haza,"[World Music, Gospel/Religioso]",58.0,0.0,/ofra-haza/
2486,Miriam Makeba,"[World Music, Black Music, Blues]",17.0,0.0,/miriam-makeba/
2487,Freddie Aguilar,[World Music],61.0,0.0,/freddie-aguilar/
2488,Johnny Clegg,"[World Music, Gospel/Religioso]",34.0,0.0,/clegg-johnny/

In [11]:
#
# Filter out unneeded or irrelevant genres
#
replaceable = [
    'Romântico', 'Gospel/Religioso', 'Trilha Sonora', 'Rock Alternativo', 'Clássico', 
    'Progressivo', 'Tecnopop', 'Gótico', 'Infantil', 'Psicodelia',
    'Soul Music', 'Hard Rock', 'Punk Rock', 'Soft Rock', 'Trip-hop'
    
]
replacewith = [
    'Romantic' , "Gospel", 'Soundtack', "Rock", 'Classic',
    "Progressive Music", 'Pop', 'Rock', "Children's music", "Psychedelic music",
    'Soul', 'Rock', 'Rock', 'Rock', 'Hip Hop'
]

# all genres with 5 or less songs, and presumed to be majority non-English
deleteable = [
    "Axé", "K-Pop/K-Rock", "J-Pop/J-Rock", "MPB", "Sertanejo", "Bossa Nova", "Brazillian Punk",
    "Samba", "COLETÂNEA", "Jovem Guarda", "Pagode", "Velha Guarda", "Fado", "Kizomba", "Regional", "Electro Swing",
    "Trap", "Forró", 'Funk Carioca', 'Pós-Punk', 'New Age'
]

# similar to list above, but only take out specified genre, not whole row of data
semi_deleteable = [
    "Black Music", " Black Music ", "World Music", " World Music ", "Piano Rock", "Post-punk", "Power-Pop", "nan"
]

for i in range(len(artists['Genres'])):
    ltemp = artists['Genres'][i]
    for j in range(len(ltemp)):
        gen = ltemp[j].strip()
        # check for deleteable words
        if gen in deleteable:
            artists.drop([i], inplace=True)
            break
        # check for replaceable words
        if gen in replaceable:
            temp = replaceable.index(gen)
            ltemp[j] = str(replacewith[temp])

for i in range(len(artists['Genres'])):
    ltemp = artists['Genres'].iloc[i]
    j = 0
    while j < len(ltemp):
        # check for redundant genres
        gen = ltemp[j].lstrip()
        if gen in semi_deleteable or gen.strip() in semi_deleteable:
            ltemp.remove(ltemp[j])
            artists['Genres'].iloc[i] = ltemp
        j += 1
artists.reset_index(drop=True, inplace=True)
artists

C:\Users\shull\anaconda3\lib\site-packages\pandas\core\indexing.py:1637: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

,Artist,Genres,Songs,Popularity,Link
0,Beyoncé,"[Pop, R&B]",276.0,205.5,/beyonce/
1,Bruno Mars,"[R&B, Pop]",122.0,62.5,/bruno-mars/
2,Rihanna,"[Pop, R&B]",246.0,51.2,/rihanna/
3,50 Cent,"[Hip Hop, Rap]",469.0,40.7,/50-cent/
4,John Legend,"[R&B, Soul]",169.0,44.5,/john-legend/
...,...,...,...,...,...
2109,Fela Kuti,[],9.0,0.0,/fela-kuti/
2110,Ofra Haza,[Gospel],58.0,0.0,/ofra-haza/
2111,Miriam Makeba,"[ Black Music, Blues]",17.0,0.0,/miriam-makeba/
2112,Freddie Aguilar,[],61.0,0.0,/freddie-aguilar/
2113,Johnny Clegg,[Gospel],34.0,0.0,/clegg-johnny/

In [12]:
# one more time, clear all empty rows
for i in range(artists.shape[0]):
    genres_list = artists['Genres'].loc[i]
    if len(genres_list) == 0:
        artists.drop([i], inplace=True)
artists.reset_index(drop=True, inplace=True)
artists

,Artist,Genres,Songs,Popularity,Link
0,Beyoncé,"[Pop, R&B]",276.0,205.5,/beyonce/
1,Bruno Mars,"[R&B, Pop]",122.0,62.5,/bruno-mars/
2,Rihanna,"[Pop, R&B]",246.0,51.2,/rihanna/
3,50 Cent,"[Hip Hop, Rap]",469.0,40.7,/50-cent/
4,John Legend,"[R&B, Soul]",169.0,44.5,/john-legend/
...,...,...,...,...,...
2099,Matoma,[Tropical House],35.0,0.1,/matoma/
2100,Khaled,"[ Indie, Dance]",21.0,1.0,/khaled/
2101,Ofra Haza,[Gospel],58.0,0.0,/ofra-haza/
2102,Miriam Makeba,"[ Black Music, Blues]",17.0,0.0,/miriam-makeba/
2103,Johnny Clegg,[Gospel],34.0,0.0,/clegg-johnny/

In [13]:
# just in case, any genres that are slashed gets randomized by chance
for i in range(artists.shape[0]):
    for j in range(len(artists['Genres'].loc[i])):
        if "/" in artists['Genres'].loc[i][j]:
            lit = artists['Genres'].loc[i][j].split("/")
            randomized = np.random.choice([0,1])
            artists['Genres'].loc[i][j] = lit[0] if randomized == 0 else lit[1]

In [14]:
# last but not least, take out the songs and popularity columns
artists.drop(['Songs', 'Popularity'], axis=1, inplace=True)
lyrics.drop(['SName', 'Lyric'], axis=1, inplace=True)

C:\Users\shull\anaconda3\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [15]:
artists.shape

(2104, 3)

In [16]:
lyrics.shape

(191814, 2)

In [17]:
# get all genres
genreset = {}

genredata = artists['Genres']
for row in genredata:
    for item in row:
        item = str(item).strip()
        genreset.update({item:genreset.get(item)+1} if item in genreset.keys() else {item:1})

all_genres = pd.DataFrame.from_dict(genreset, orient='index', columns=['Count'])
all_genres['Genre'] = genreset.keys()
all_genres.reset_index(drop=True, inplace=True)
all_genres = all_genres.sort_values(by=['Count'], ascending=False)
all_genres.reset_index(drop=True, inplace=True)
print(all_genres.shape[0])
all_genres

46

    Count              Genre
0    1201               Rock
1     596                Pop
2     254              Indie
3     203        Heavy Metal
4     202            Hip Hop
5     193           Romantic
6     180              Dance
7     164        Electronica
8     149                Rap
9     144                R&B
10    140             Gospel
11    118          Soundtack
12     95               Folk
13     91               Soul
14     86           Hardcore
15     74            Country
16     70              Blues
17     64             Reggae
18     46              House
19     42               Funk
20     40               Jazz
21     38  Progressive Music
22     31   Children's music
23     31              Disco
24     30       Instrumental
25     29         Rockabilly
26     28            Emocore
27     27             Grunge
28     27  Psychedelic music
29     25         Surf Music
30     24            Classic
31     23           New Wave
32     19           Trip-Hop
33     18               Punk
34     17             Trance
35     14           Chillout
36     14                Ska
37     11          Reggaeton
38     10         Industrial
39      9       Classic Rock
40      7              Metal
41      6              Lo-fi
42      6          Post-Rock
43      5     Tropical House
44      1        World Music
45      1        Black Music

In [18]:
# we won't need the artist name, or the song name (lyrics)
lyrics.rename(columns={"ALink": "Link"}, inplace=True)
artists_lyrics = pd.merge(artists,lyrics)
artists_lyrics

C:\Users\shull\anaconda3\lib\site-packages\pandas\core\frame.py:4441: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

,Artist,Genres,Link,SLink
0,Beyoncé,"[Pop, R&B]",/beyonce/,/beyonce/halo.html
1,Beyoncé,"[Pop, R&B]",/beyonce/,/beyonce/partition.html
2,Beyoncé,"[Pop, R&B]",/beyonce/,/beyonce/if-i-were-a-boy.html
3,Beyoncé,"[Pop, R&B]",/beyonce/,/beyonce/love-on-top.html
4,Beyoncé,"[Pop, R&B]",/beyonce/,/beyonce/crazy-in-love.html
...,...,...,...,...
180045,Johnny Clegg,[Gospel],/clegg-johnny/,/clegg-johnny/the-waiting.html
180046,Johnny Clegg,[Gospel],/clegg-johnny/,/clegg-johnny/too-early-for-the-sky.html
180047,Johnny Clegg,[Gospel],/clegg-johnny/,/clegg-johnny/warsaw-1943-i-never-betrayed-the...
180048,Johnny Clegg,[Gospel],/clegg-johnny/,/clegg-johnny/when-the-system-has-fallen.html
180049,Johnny Clegg,[Gospel],/clegg-johnny/,/clegg-johnny/woman-be-my-country.html

In [19]:
from sklearn.utils import shuffle

# need this for later
SELECT = 50000

In [20]:
#####
# for the last portion of this worksheet, filter out lyrics using web scraping

In [21]:
# SOURCE: https://www.delftstack.com/howto/python/remove-numbers-from-string-python/
import bs4 as bs
import urllib.request
import string
from string import digits
from urllib.error import HTTPError

import nltk
nltk.download('stopwords')
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords
nltk.download('punkt')

'''
    FUNCTIONS
'''
# functions to grab URL link
def refine_lyrics(url, p):
    if p: print(f"Looking for {url} ...\n")
    try: 
        source = urllib.request.urlopen(url).read()
    except HTTPError:
        if p: 
            print("URL not found, try again.")
    try: 
        soup = bs.BeautifulSoup(source, 'lxml')
    except:
        if p: 
            print("Unable to recall source.\n")
    request = soup.find('div', {"id": 'lyrics'})
    text = request.get_text(separator=' ')
    return text

def defluff_text(src):
    temp = str(src).replace(' ', '')
    temp = temp.translate(str.maketrans("/(')\p{P}/", "/(')\p{P}/", digits)).partition('\n')[0]
    return temp 

def request_lyrics(row, prints=False):
    link = defluff_text(row['SLink'])
    url = f"{LYRIC_URL}{link}"
    ret = refine_lyrics(url, prints)
    
    almost_there = ret.split(" ")
    almost_there = [str(word).lower() for word in almost_there]
    almost_there = "".join(a+" " for a in almost_there)
    
    ret = almost_there
    return ret

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\shull\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\shull\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [22]:
# for INPUT (artist), before URL
def get_link(inp):
    link = artists.loc[artists['Artist'].isin([inp])]['Link'].item() if inp in artists['Artist'].values else ""
    return link

In [23]:
elims = {
    "myself", "ourselves", "yourself", "yourselves", "himself",
    "herself", "themselves", "against", "between", "further",
}
stops = set(stopwords.words('english')) - elims
for s in stops:
    s = s.translate(str.maketrans("/(')\p{P}/", "/(')\p{P}/", string.punctuation))

In [24]:
#####
# use artists_lyrics for functions above

example_row = artists_lyrics.iloc[1111]
print(example_row)

returned_string = request_lyrics(example_row)
returned_string

Artist                                      John Legend
Genres                                      [R&B, Soul]
Link                                      /john-legend/
SLink     /john-legend/dont-you-worry-bout-a-thing.html
Name: 1111, dtype: object

"everybody's got a thing but some don't know how to handle it always reachin' out in vain just taking the things not worth havin' chorus: but don't you worry 'bout a thing don't you worry 'bout a thing (don't you worry, baby) 'cause i'll be standing on the side when you check it out they say your style of life's a drag and that you must go other places just don't you feel too bad when you get fooled by smiling faces chorus when you get off your trip don't you worry 'bout a thing don't you worry 'bout a thing chorus everybody needs a change a chance to check out the new you're the only one who see the changes you take yourself through don't you worry 'bout a thing don't you worry 'bout a thing (sweet baby) 'cause i'll be standin' in the wings when you check it out don't you worry 'bout a thing don't you worry 'bout a thing don't worry, don't worry, don't worry 'cause i'll be right here waitin' for you baby "

In [25]:
# count each word in the song
try:
    import enchant
except ModuleNotFoundError:
    !{sys.executable} -m pip install pyenchant
    import enchant
    
denchant = enchant.Dict("en_US")

def stopStopWords(d):
    new_d = {**d}
    for k in new_d.keys():
        if k in stops:
            del new_d[k]
    return {**new_d}

def countEachWord(source):
    words = source.split(' ')
    rset = {}
    
    words = [str(word).lower().strip() for word in words]
    
    for i in range(len(words)):        
        #https://datagy.io/python-remove-punctuation-from-string/
        words[i] = words[i].translate(str.maketrans("/(')\p{P}/", "/(')\p{P}/", string.punctuation))
        
        if len(words[i]) == 0:
            continue
        if denchant.check(words[i]) == False:
            continue
        if words[i] in stops:
            continue
        
        # put to word set, count how many times a word is used.
        rset.update({words[i]:rset.get(words[i])+1} if words[i] in rset else {words[i]:1})
    return rset

wordset = countEachWord(returned_string)

In [26]:
import time
from datetime import datetime

GW = "GenreWords"  # folder
GWDICT = {}  # dictionary

# get dictionary for all genre words and 
# store all data into multiple .csv files using 'GenreWords':
def tabulateDict(genres, lyrics):
    assert type(genres) == list and type(lyrics) == dict
    for g in genres:
        g = g.strip()
        
        # introduce new genre if unavailable
        if g not in GWDICT.keys():
            GWDICT[g] = lyrics
            continue
            
        # existing genre, make deep copy of dictionary
        newset = {**GWDICT[g]}
        for l in lyrics.keys():
            newset[l] = lyrics[l] if l not in newset else newset[l] + lyrics[l]
        GWDICT[g] = {**newset}

In [27]:
confirm_long_run = str(input("Do you agree to run the next cell? Type 'Agree' to confirm >>>"))
if confirm_long_run != "Agree":
    raise Exception

Do you agree to run the next cell? Type 'Agree' to confirm >>>Agree

In [ ]:
%%time

shuffled_artists_lyrics = shuffle(artists_lyrics)
shuffled_artists_lyrics[0:SELECT]
shuffled_artists_lyrics.reset_index(drop=True, inplace=True)
shuffled_artists_lyrics['Lyric'] = ""
shuffled_artists_lyrics['Set'] = ""

actual_count = 0
for i in range(SELECT):
    tmp = shuffled_artists_lyrics.iloc[i]
    try:
        ly = request_lyrics(tmp)
    except:
        shuffled_artists_lyrics.drop([i])
        continue
    st = countEachWord(ly)
    tabulateDict(tmp['Genres'], st)
    shuffled_artists_lyrics['Lyric'][i] = ly
    shuffled_artists_lyrics['Set'][i] = st
    #print(i, ": ", round((i / SELECT) * 100, 4), "\t time: ", datetime.now().strftime("%H:%M:%S"))
    actual_count += 1
    
if actual_count < artists_lyrics.shape[0]:
    shuffled_artists_lyrics = shuffled_artists_lyrics[0:actual_count]
    
shuffled_artists_lyrics.reset_index(drop=True, inplace=True)

In [29]:
shuffled_artists_lyrics

,Artist,Genres,Link,SLink,Lyric,Set
0,Wolf Alice,"[Rock, Indie]",/wolf-alice/,/wolf-alice/bros.html,shake your hair have some fun forget our mothe...,"{'shake': 1, 'hair': 2, 'fun': 1, 'forget': 2,..."
1,Marié Digby,"[Pop, Romantic, Pop]",/marie-digby/,/marie-digby/you-give-me-something.html,you only stay with me in the morning you only ...,"{'stay': 1, 'morning': 1, 'hold': 1, 'sleep': ..."
2,Boyce Avenue,"[Pop, Romantic]",/boyce-avenue/,/boyce-avenue/send-my-love-to-your-new-lover.html,"this was all you, none of it me you put your h...","{'none': 1, 'put': 1, 'hands': 1, 'body': 1, '..."
3,Smash Mouth,"[Rock, Rock]",/smash-mouth/,/smash-mouth/i-wanna-be-like-you.html,can you hear it? yeah man now i'm the king of ...,"{'hear': 2, 'yeah': 4, 'man': 3, 'king': 1, 's..."
4,Dawes,"[Folk, Indie, Rock]",/dawes/,/dawes/when-you-call-my-name.html,if all my lovers sing the big words and all my...,"{'lovers': 1, 'sing': 1, 'big': 1, 'words': 1,..."
...,...,...,...,...,...,...
46545,James Arthur,"[Pop, Soul]",/james-arthur/,/james-arthur/prisoner.html,if i'm underneath the table then pour me anoth...,"{'underneath': 1, 'table': 1, 'pour': 2, 'anot..."
46546,Barry Manilow,[Romantic],/barry-manilow/,/barry-manilow/we-wish-you-a-merry-christmas.html,we wish you a merry christmas we wish you a me...,"{'wish': 6, 'merry': 6, 'happy': 6, 'new': 6, ..."
46547,Wanessa Camargo,"[Dance, Romantic, Pop]",/wanessa-camargo/,/wanessa-camargo/get-loudi.html,get it right! we'll party until the morning li...,"{'get': 76, 'right': 1, 'well': 8, 'party': 1,..."
46548,Tony Bennett & Lady Gaga,[Jazz],/tony-bennett-lady-gaga/,/tony-bennett-lady-gaga/they-all-laughed.html,they all laughed at christopher columbus when ...,"{'laughed': 9, 'said': 6, 'world': 1, 'round':..."
46549,10000 Maniacs,"[Rock, Pop, Electronica]",/10000-maniacs/,/10000-maniacs/time-turns.html,,

In [30]:
render_words = pd.DataFrame(GWDICT)
render_words

,Rock,Indie,Pop,Romantic,Folk,Grunge,Jazz,Classic,New Wave,Rap,...,Trance,Ska,Instrumental,Chillout,Tropical House,Post-Rock,Lo-fi,Black Music,Reggaeton,World Music
shake,1528.0,189.0,1568.0,257.0,94.0,21.0,35.0,4.0,11.0,726.0,...,4.0,5.0,2.0,15.0,NaN,NaN,NaN,NaN,7.0,NaN
hair,1117.0,247.0,808.0,233.0,177.0,17.0,40.0,7.0,26.0,287.0,...,NaN,6.0,7.0,3.0,1.0,1.0,NaN,NaN,1.0,NaN
fun,1540.0,259.0,976.0,190.0,89.0,24.0,66.0,11.0,34.0,279.0,...,2.0,21.0,8.0,5.0,NaN,NaN,NaN,NaN,1.0,NaN
forget,2453.0,372.0,1508.0,485.0,218.0,75.0,115.0,54.0,33.0,436.0,...,33.0,14.0,14.0,30.0,1.0,3.0,2.0,NaN,1.0,NaN
mothers,289.0,55.0,102.0,43.0,54.0,5.0,13.0,4.0,10.0,78.0,...,1.0,2.0,1.0,2.0,NaN,5.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
repulsively,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
creature’s,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
investigative,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wallabies,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
usable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN

In [31]:
shuffled_artists_lyrics.to_csv("complete-artists-lyrics.csv")
render_words.to_csv("all-genre-words.csv")
all_genres.to_csv("genre-list.csv")